/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 123
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 65
#define ALIAS_COUNT 0
#define TOKEN_COUNT 37
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 35
#define MAX_ALIAS_SEQUENCE_LENGTH 11
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 48
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_newline = 2,
  sym_identifier = 3,
  anon_sym_DQUOTE = 4,
  aux_sym_string_literal_token1 = 5,
  aux_sym_string_literal_token2 = 6,
  sym_integer_literal = 7,
  anon_sym_LBRACK = 8,
  anon_sym_COMMA = 9,
  anon_sym_RBRACK = 10,
  sym_sortby_expression = 11,
  sym_keyword_palette = 12,
  sym_keyword_bitmap = 13,
  sym_keyword_tileset = 14,
  sym_keyword_tilemap = 15,
  sym_keyword_map = 16,
  sym_keyword_objects = 17,
  sym_keyword_image = 18,
  sym_keyword_sprite = 19,
  sym_keyword_xgm = 20,
  sym_keyword_xgm2 = 21,
  sym_keyword_wav = 22,
  sym_keyword_bin = 23,
  sym_keyword_align = 24,
  sym_keyword_ungroup = 25,
  sym_keyword_near = 26,
  sym_keyword_compression = 27,
  sym_keyword_optimization = 28,
  sym_keyword_ordering = 29,
  sym_keyword_export = 30,
  sym_keyword_collision = 31,
  aux_sym_keyword_far_token1 = 32,
  sym_keyword_sprite_optimization_type = 33,
  sym_keyword_sprite_optimization_level = 34,
  sym_keyword_xgm_timing = 35,
  sym_keyword_wav_driver = 36,
  sym_source_file = 37,
  sym__statement = 38,
  sym_string_literal = 39,
  sym_integer_array_literal = 40,
  sym_integer_array2d_literal = 41,
  sym_sprite_time_expression = 42,
  sym_keyword_far = 43,
  sym_keyword_sprite_optimization_duplicate = 44,
  sym_palette_statement = 45,
  sym_bitmap_statement = 46,
  sym_tileset_statement = 47,
  sym_tilemap_statement = 48,
  sym_map_statement = 49,
  sym_objects_statement = 50,
  sym_image_statement = 51,
  sym_sprite_statement = 52,
  sym_xgm_statement = 53,
  sym_xgm2_statement = 54,
  sym_wav_statement = 55,
  sym_bin_statement = 56,
  sym_align_statement = 57,
  sym_ungroup_statement = 58,
  sym_near_statement = 59,
  aux_sym_source_file_repeat1 = 60,
  aux_sym_string_literal_repeat1 = 61,
  aux_sym_integer_array_literal_repeat1 = 62,
  aux_sym_integer_array2d_literal_repeat1 = 63,
  aux_sym_xgm2_statement_repeat1 = 64,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_newline] = "newline",
  [sym_identifier] = "identifier",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [aux_sym_string_literal_token2] = "string_literal_token2",
  [sym_integer_literal] = "integer_literal",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [sym_sortby_expression] = "sortby_expression",
  [sym_keyword_palette] = "keyword_palette",
  [sym_keyword_bitmap] = "keyword_bitmap",
  [sym_keyword_tileset] = "keyword_tileset",
  [sym_keyword_tilemap] = "keyword_tilemap",
  [sym_keyword_map] = "keyword_map",
  [sym_keyword_objects] = "keyword_objects",
  [sym_keyword_image] = "keyword_image",
  [sym_keyword_sprite] = "keyword_sprite",
  [sym_keyword_xgm] = "keyword_xgm",
  [sym_keyword_xgm2] = "keyword_xgm2",
  [sym_keyword_wav] = "keyword_wav",
  [sym_keyword_bin] = "keyword_bin",
  [sym_keyword_align] = "keyword_align",
  [sym_keyword_ungroup] = "keyword_ungroup",
  [sym_keyword_near] = "keyword_near",
  [sym_keyword_compression] = "keyword_compression",
  [sym_keyword_optimization] = "keyword_optimization",
  [sym_keyword_ordering] = "keyword_ordering",
  [sym_keyword_export] = "keyword_export",
  [sym_keyword_collision] = "keyword_collision",
  [aux_sym_keyword_far_token1] = "keyword_far_token1",
  [sym_keyword_sprite_optimization_type] = "keyword_sprite_optimization_type",
  [sym_keyword_sprite_optimization_level] = "keyword_sprite_optimization_level",
  [sym_keyword_xgm_timing] = "keyword_xgm_timing",
  [sym_keyword_wav_driver] = "keyword_wav_driver",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_string_literal] = "string_literal",
  [sym_integer_array_literal] = "integer_array_literal",
  [sym_integer_array2d_literal] = "integer_array2d_literal",
  [sym_sprite_time_expression] = "sprite_time_expression",
  [sym_keyword_far] = "keyword_far",
  [sym_keyword_sprite_optimization_duplicate] = "keyword_sprite_optimization_duplicate",
  [sym_palette_statement] = "palette_statement",
  [sym_bitmap_statement] = "bitmap_statement",
  [sym_tileset_statement] = "tileset_statement",
  [sym_tilemap_statement] = "tilemap_statement",
  [sym_map_statement] = "map_statement",
  [sym_objects_statement] = "objects_statement",
  [sym_image_statement] = "image_statement",
  [sym_sprite_statement] = "sprite_statement",
  [sym_xgm_statement] = "xgm_statement",
  [sym_xgm2_statement] = "xgm2_statement",
  [sym_wav_statement] = "wav_statement",
  [sym_bin_statement] = "bin_statement",
  [sym_align_statement] = "align_statement",
  [sym_ungroup_statement] = "ungroup_statement",
  [sym_near_statement] = "near_statement",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
  [aux_sym_integer_array_literal_repeat1] = "integer_array_literal_repeat1",
  [aux_sym_integer_array2d_literal_repeat1] = "integer_array2d_literal_repeat1",
  [aux_sym_xgm2_statement_repeat1] = "xgm2_statement_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_newline] = sym_newline,
  [sym_identifier] = sym_identifier,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [aux_sym_string_literal_token2] = aux_sym_string_literal_token2,
  [sym_integer_literal] = sym_integer_literal,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_sortby_expression] = sym_sortby_expression,
  [sym_keyword_palette] = sym_keyword_palette,
  [sym_keyword_bitmap] = sym_keyword_bitmap,
  [sym_keyword_tileset] = sym_keyword_tileset,
  [sym_keyword_tilemap] = sym_keyword_tilemap,
  [sym_keyword_map] = sym_keyword_map,
  [sym_keyword_objects] = sym_keyword_objects,
  [sym_keyword_image] = sym_keyword_image,
  [sym_keyword_sprite] = sym_keyword_sprite,
  [sym_keyword_xgm] = sym_keyword_xgm,
  [sym_keyword_xgm2] = sym_keyword_xgm2,
  [sym_keyword_wav] = sym_keyword_wav,
  [sym_keyword_bin] = sym_keyword_bin,
  [sym_keyword_align] = sym_keyword_align,
  [sym_keyword_ungroup] = sym_keyword_ungroup,
  [sym_keyword_near] = sym_keyword_near,
  [sym_keyword_compression] = sym_keyword_compression,
  [sym_keyword_optimization] = sym_keyword_optimization,
  [sym_keyword_ordering] = sym_keyword_ordering,
  [sym_keyword_export] = sym_keyword_export,
  [sym_keyword_collision] = sym_keyword_collision,
  [aux_sym_keyword_far_token1] = aux_sym_keyword_far_token1,
  [sym_keyword_sprite_optimization_type] = sym_keyword_sprite_optimization_type,
  [sym_keyword_sprite_optimization_level] = sym_keyword_sprite_optimization_level,
  [sym_keyword_xgm_timing] = sym_keyword_xgm_timing,
  [sym_keyword_wav_driver] = sym_keyword_wav_driver,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_string_literal] = sym_string_literal,
  [sym_integer_array_literal] = sym_integer_array_literal,
  [sym_integer_array2d_literal] = sym_integer_array2d_literal,
  [sym_sprite_time_expression] = sym_sprite_time_expression,
  [sym_keyword_far] = sym_keyword_far,
  [sym_keyword_sprite_optimization_duplicate] = sym_keyword_sprite_optimization_duplicate,
  [sym_palette_statement] = sym_palette_statement,
  [sym_bitmap_statement] = sym_bitmap_statement,
  [sym_tileset_statement] = sym_tileset_statement,
  [sym_tilemap_statement] = sym_tilemap_statement,
  [sym_map_statement] = sym_map_statement,
  [sym_objects_statement] = sym_objects_statement,
  [sym_image_statement] = sym_image_statement,
  [sym_sprite_statement] = sym_sprite_statement,
  [sym_xgm_statement] = sym_xgm_statement,
  [sym_xgm2_statement] = sym_xgm2_statement,
  [sym_wav_statement] = sym_wav_statement,
  [sym_bin_statement] = sym_bin_statement,
  [sym_align_statement] = sym_align_statement,
  [sym_ungroup_statement] = sym_ungroup_statement,
  [sym_near_statement] = sym_near_statement,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
  [aux_sym_integer_array_literal_repeat1] = aux_sym_integer_array_literal_repeat1,
  [aux_sym_integer_array2d_literal_repeat1] = aux_sym_integer_array2d_literal_repeat1,
  [aux_sym_xgm2_statement_repeat1] = aux_sym_xgm2_statement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_sortby_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_palette] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_bitmap] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_tileset] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_tilemap] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_map] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_objects] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_image] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_sprite] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_xgm] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_xgm2] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_wav] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_bin] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_align] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_ungroup] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_near] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_compression] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_optimization] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_ordering] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_export] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_collision] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_keyword_far_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_keyword_sprite_optimization_type] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_sprite_optimization_level] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_xgm_timing] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_wav_driver] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_array_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_array2d_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_sprite_time_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_far] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_sprite_optimization_duplicate] = {
    .visible = true,
    .named = true,
  },
  [sym_palette_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_bitmap_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_tileset_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_tilemap_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_map_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_objects_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_image_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_sprite_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_xgm_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_xgm2_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_wav_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_bin_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_align_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_ungroup_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_near_statement] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_array_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_integer_array2d_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_xgm2_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_align = 1,
  field_collision = 2,
  field_compression = 3,
  field_decl_type = 4,
  field_driver = 5,
  field_export = 6,
  field_far = 7,
  field_field_defs = 8,
  field_file = 9,
  field_fill = 10,
  field_height = 11,
  field_img_file = 12,
  field_layer_id = 13,
  field_map_base = 14,
  field_map_compression = 15,
  field_map_opt = 16,
  field_name = 17,
  field_opt = 18,
  field_opt_duplicate = 19,
  field_opt_level = 20,
  field_opt_type = 21,
  field_options = 22,
  field_ordering = 23,
  field_out_rate = 24,
  field_size_align = 25,
  field_sortby = 26,
  field_tileset_id = 27,
  field_time = 28,
  field_timing = 29,
  field_tmx_file = 30,
  field_ts_compression = 31,
  field_type_filter = 32,
  field_value = 33,
  field_wav_file = 34,
  field_width = 35,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_align] = "align",
  [field_collision] = "collision",
  [field_compression] = "compression",
  [field_decl_type] = "decl_type",
  [field_driver] = "driver",
  [field_export] = "export",
  [field_far] = "far",
  [field_field_defs] = "field_defs",
  [field_file] = "file",
  [field_fill] = "fill",
  [field_height] = "height",
  [field_img_file] = "img_file",
  [field_layer_id] = "layer_id",
  [field_map_base] = "map_base",
  [field_map_compression] = "map_compression",
  [field_map_opt] = "map_opt",
  [field_name] = "name",
  [field_opt] = "opt",
  [field_opt_duplicate] = "opt_duplicate",
  [field_opt_level] = "opt_level",
  [field_opt_type] = "opt_type",
  [field_options] = "options",
  [field_ordering] = "ordering",
  [field_out_rate] = "out_rate",
  [field_size_align] = "size_align",
  [field_sortby] = "sortby",
  [field_tileset_id] = "tileset_id",
  [field_time] = "time",
  [field_timing] = "timing",
  [field_tmx_file] = "tmx_file",
  [field_ts_compression] = "ts_compression",
  [field_type_filter] = "type_filter",
  [field_value] = "value",
  [field_wav_file] = "wav_file",
  [field_width] = "width",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 3},
  [7] = {.index = 11, .length = 3},
  [8] = {.index = 14, .length = 3},
  [9] = {.index = 17, .length = 3},
  [10] = {.index = 20, .length = 3},
  [11] = {.index = 23, .length = 2},
  [12] = {.index = 25, .length = 3},
  [13] = {.index = 28, .length = 3},
  [14] = {.index = 31, .length = 4},
  [15] = {.index = 35, .length = 4},
  [16] = {.index = 39, .length = 4},
  [17] = {.index = 43, .length = 4},
  [18] = {.index = 47, .length = 4},
  [19] = {.index = 51, .length = 4},
  [20] = {.index = 55, .length = 4},
  [21] = {.index = 59, .length = 4},
  [22] = {.index = 63, .length = 4},
  [23] = {.index = 67, .length = 5},
  [24] = {.index = 72, .length = 5},
  [25] = {.index = 77, .length = 5},
  [26] = {.index = 82, .length = 5},
  [27] = {.index = 87, .length = 5},
  [28] = {.index = 92, .length = 5},
  [29] = {.index = 97, .length = 5},
  [30] = {.index = 102, .length = 5},
  [31] = {.index = 107, .length = 5},
  [32] = {.index = 112, .length = 5},
  [33] = {.index = 117, .length = 6},
  [34] = {.index = 123, .length = 6},
  [35] = {.index = 129, .length = 6},
  [36] = {.index = 135, .length = 6},
  [37] = {.index = 141, .length = 6},
  [38] = {.index = 147, .length = 6},
  [39] = {.index = 153, .length = 6},
  [40] = {.index = 159, .length = 7},
  [41] = {.index = 166, .length = 7},
  [42] = {.index = 173, .length = 7},
  [43] = {.index = 180, .length = 7},
  [44] = {.index = 187, .length = 7},
  [45] = {.index = 194, .length = 8},
  [46] = {.index = 202, .length = 9},
  [47] = {.index = 211, .length = 10},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_value, 1},
  [1] =
    {field_file, 2},
    {field_name, 1},
  [3] =
    {field_img_file, 2},
    {field_name, 1},
  [5] =
    {field_file, 0},
  [6] =
    {field_file, 2, .inherited = true},
    {field_name, 1},
  [8] =
    {field_compression, 3},
    {field_img_file, 2},
    {field_name, 1},
  [11] =
    {field_compression, 3},
    {field_file, 2},
    {field_name, 1},
  [14] =
    {field_img_file, 2},
    {field_name, 1},
    {field_tileset_id, 3},
  [17] =
    {field_layer_id, 3},
    {field_name, 1},
    {field_tmx_file, 2},
  [20] =
    {field_file, 2},
    {field_name, 1},
    {field_timing, 3},
  [23] =
    {field_file, 0, .inherited = true},
    {field_file, 1, .inherited = true},
  [25] =
    {field_driver, 3},
    {field_name, 1},
    {field_wav_file, 2},
  [28] =
    {field_align, 3},
    {field_file, 2},
    {field_name, 1},
  [31] =
    {field_compression, 3},
    {field_file, 2},
    {field_name, 1},
    {field_opt, 4},
  [35] =
    {field_compression, 4},
    {field_img_file, 2},
    {field_name, 1},
    {field_tileset_id, 3},
  [39] =
    {field_layer_id, 3},
    {field_name, 1},
    {field_tmx_file, 2},
    {field_ts_compression, 4},
  [43] =
    {field_field_defs, 4},
    {field_layer_id, 3},
    {field_name, 1},
    {field_tmx_file, 2},
  [47] =
    {field_compression, 3},
    {field_img_file, 2},
    {field_map_opt, 4},
    {field_name, 1},
  [51] =
    {field_height, 4},
    {field_img_file, 2},
    {field_name, 1},
    {field_width, 3},
  [55] =
    {field_file, 2},
    {field_name, 1},
    {field_options, 4},
    {field_timing, 3},
  [59] =
    {field_driver, 3},
    {field_name, 1},
    {field_out_rate, 4},
    {field_wav_file, 2},
  [63] =
    {field_align, 3},
    {field_file, 2},
    {field_name, 1},
    {field_size_align, 4},
  [67] =
    {field_compression, 3},
    {field_file, 2},
    {field_name, 1},
    {field_opt, 4},
    {field_ordering, 5},
  [72] =
    {field_layer_id, 3},
    {field_map_compression, 5},
    {field_name, 1},
    {field_tmx_file, 2},
    {field_ts_compression, 4},
  [77] =
    {field_compression, 4},
    {field_img_file, 2},
    {field_map_opt, 5},
    {field_name, 1},
    {field_tileset_id, 3},
  [82] =
    {field_compression, 4},
    {field_img_file, 2},
    {field_map_base, 5},
    {field_name, 1},
    {field_tileset_id, 3},
  [87] =
    {field_field_defs, 4},
    {field_layer_id, 3},
    {field_name, 1},
    {field_sortby, 5},
    {field_tmx_file, 2},
  [92] =
    {field_decl_type, 5},
    {field_field_defs, 4},
    {field_layer_id, 3},
    {field_name, 1},
    {field_tmx_file, 2},
  [97] =
    {field_compression, 3},
    {field_img_file, 2},
    {field_map_base, 5},
    {field_map_opt, 4},
    {field_name, 1},
  [102] =
    {field_compression, 5},
    {field_height, 4},
    {field_img_file, 2},
    {field_name, 1},
    {field_width, 3},
  [107] =
    {field_driver, 3},
    {field_far, 5},
    {field_name, 1},
    {field_out_rate, 4},
    {field_wav_file, 2},
  [112] =
    {field_align, 3},
    {field_file, 2},
    {field_fill, 5},
    {field_name, 1},
    {field_size_align, 4},
  [117] =
    {field_compression, 3},
    {field_export, 6},
    {field_file, 2},
    {field_name, 1},
    {field_opt, 4},
    {field_ordering, 5},
  [123] =
    {field_layer_id, 3},
    {field_map_base, 6},
    {field_map_compression, 5},
    {field_name, 1},
    {field_tmx_file, 2},
    {field_ts_compression, 4},
  [129] =
    {field_compression, 4},
    {field_img_file, 2},
    {field_map_base, 6},
    {field_map_opt, 5},
    {field_name, 1},
    {field_tileset_id, 3},
  [135] =
    {field_decl_type, 6},
    {field_field_defs, 4},
    {field_layer_id, 3},
    {field_name, 1},
    {field_sortby, 5},
    {field_tmx_file, 2},
  [141] =
    {field_decl_type, 5},
    {field_field_defs, 4},
    {field_layer_id, 3},
    {field_name, 1},
    {field_tmx_file, 2},
    {field_type_filter, 6},
  [147] =
    {field_compression, 5},
    {field_height, 4},
    {field_img_file, 2},
    {field_name, 1},
    {field_time, 6},
    {field_width, 3},
  [153] =
    {field_align, 3},
    {field_compression, 6},
    {field_file, 2},
    {field_fill, 5},
    {field_name, 1},
    {field_size_align, 4},
  [159] =
    {field_compression, 4},
    {field_img_file, 2},
    {field_map_base, 6},
    {field_map_opt, 5},
    {field_name, 1},
    {field_ordering, 7},
    {field_tileset_id, 3},
  [166] =
    {field_layer_id, 3},
    {field_map_base, 6},
    {field_map_compression, 5},
    {field_name, 1},
    {field_ordering, 7},
    {field_tmx_file, 2},
    {field_ts_compression, 4},
  [173] =
    {field_decl_type, 6},
    {field_field_defs, 4},
    {field_layer_id, 3},
    {field_name, 1},
    {field_sortby, 5},
    {field_tmx_file, 2},
    {field_type_filter, 7},
  [180] =
    {field_collision, 7},
    {field_compression, 5},
    {field_height, 4},
    {field_img_file, 2},
    {field_name, 1},
    {field_time, 6},
    {field_width, 3},
  [187] =
    {field_align, 3},
    {field_compression, 6},
    {field_far, 7},
    {field_file, 2},
    {field_fill, 5},
    {field_name, 1},
    {field_size_align, 4},
  [194] =
    {field_collision, 7},
    {field_compression, 5},
    {field_height, 4},
    {field_img_file, 2},
    {field_name, 1},
    {field_opt_type, 8},
    {field_time, 6},
    {field_width, 3},
  [202] =
    {field_collision, 7},
    {field_compression, 5},
    {field_height, 4},
    {field_img_file, 2},
    {field_name, 1},
    {field_opt_level, 9},
    {field_opt_type, 8},
    {field_time, 6},
    {field_width, 3},
  [211] =
    {field_collision, 7},
    {field_compression, 5},
    {field_height, 4},
    {field_img_file, 2},
    {field_name, 1},
    {field_opt_duplicate, 10},
    {field_opt_level, 9},
    {field_opt_type, 8},
    {field_time, 6},
    {field_width, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 7,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 11,
  [20] = 13,
  [21] = 21,
  [22] = 8,
  [23] = 13,
  [24] = 8,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 7,
  [81] = 11,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(192);
      ADVANCE_MAP(
        '\n', 194,
        '\r', 1,
        '"', 197,
        '#', 193,
        ',', 205,
        '-', 13,
        '/', 12,
        '0', 202,
        '1', 203,
        '2', 203,
        '3', 203,
        'A', 88,
        'B', 23,
        'C', 76,
        'D', 52,
        'F', 19,
        'I', 114,
        'L', 183,
        'M', 20,
        'N', 64,
        'O', 40,
        'P', 30,
        'R', 128,
        'S', 107,
        'T', 82,
        'U', 122,
        'W', 21,
        'X', 69,
        '[', 204,
        '\\', 190,
        ']', 206,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('4' <= lookahead && lookahead <= '9')) ADVANCE(203);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(194);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 194,
        '\r', 1,
        '"', 197,
        '#', 193,
        '-', 13,
        '/', 12,
        '0', 202,
        'A', 135,
        'B', 51,
        'F', 18,
        'L', 183,
        'N', 130,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '1' ||
          lookahead == '2') ADVANCE(203);
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(203);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\n', 194,
        '\r', 1,
        '"', 196,
        '#', 193,
        '-', 13,
        '/', 12,
        'A', 103,
        'B', 51,
        'D', 52,
        'F', 18,
        'L', 183,
        'N', 130,
        'P', 42,
        'X', 73,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '2')) ADVANCE(223);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '\n', 194,
        '\r', 1,
        '#', 193,
        '-', 14,
        '/', 12,
        'A', 176,
        'N', 161,
        'P', 34,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(231);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(194);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(193);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == 'A') ADVANCE(102);
      if (lookahead == 'D') ADVANCE(169);
      if (lookahead == 'N') ADVANCE(134);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '2')) ADVANCE(224);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '\n', 194,
        '\r', 1,
        '#', 193,
        '/', 12,
        'B', 22,
        'N', 133,
        'S', 143,
        'T', 81,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '3')) ADVANCE(229);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(194);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(193);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == 'F') ADVANCE(37);
      if (lookahead == 'T') ADVANCE(144);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(7);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(226);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(194);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(193);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == 'F') ADVANCE(35);
      if (lookahead == 'M') ADVANCE(24);
      if (lookahead == 'S') ADVANCE(106);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '3')) ADVANCE(230);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(207);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '"') ADVANCE(196);
      if (lookahead == '#') ADVANCE(193);
      if (lookahead == '/') ADVANCE(200);
      if (lookahead == '\\') ADVANCE(190);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(199);
      if (lookahead != 0) ADVANCE(198);
      END_STATE();
    case 11:
      if (lookahead == '#') ADVANCE(193);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(195);
      END_STATE();
    case 12:
      if (lookahead == '/') ADVANCE(193);
      END_STATE();
    case 13:
      if (lookahead == '1') ADVANCE(223);
      END_STATE();
    case 14:
      if (lookahead == '1') ADVANCE(231);
      END_STATE();
    case 15:
      if (lookahead == '2') ADVANCE(233);
      END_STATE();
    case 16:
      if (lookahead == '4') ADVANCE(178);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(189);
      END_STATE();
    case 18:
      if (lookahead == 'A') ADVANCE(151);
      END_STATE();
    case 19:
      if (lookahead == 'A') ADVANCE(95);
      END_STATE();
    case 20:
      if (lookahead == 'A') ADVANCE(137);
      if (lookahead == 'E') ADVANCE(49);
      END_STATE();
    case 21:
      if (lookahead == 'A') ADVANCE(177);
      END_STATE();
    case 22:
      if (lookahead == 'A') ADVANCE(98);
      END_STATE();
    case 23:
      if (lookahead == 'A') ADVANCE(98);
      if (lookahead == 'E') ADVANCE(151);
      if (lookahead == 'I') ADVANCE(118);
      if (lookahead == 'O') ADVANCE(181);
      END_STATE();
    case 24:
      if (lookahead == 'A') ADVANCE(182);
      if (lookahead == 'E') ADVANCE(49);
      END_STATE();
    case 25:
      if (lookahead == 'A') ADVANCE(138);
      END_STATE();
    case 26:
      if (lookahead == 'A') ADVANCE(145);
      END_STATE();
    case 27:
      if (lookahead == 'A') ADVANCE(174);
      END_STATE();
    case 28:
      if (lookahead == 'A') ADVANCE(124);
      END_STATE();
    case 29:
      if (lookahead == 'A') ADVANCE(72);
      END_STATE();
    case 30:
      if (lookahead == 'A') ADVANCE(91);
      if (lookahead == 'C') ADVANCE(110);
      END_STATE();
    case 31:
      if (lookahead == 'A') ADVANCE(136);
      END_STATE();
    case 32:
      if (lookahead == 'A') ADVANCE(140);
      END_STATE();
    case 33:
      if (lookahead == 'A') ADVANCE(108);
      END_STATE();
    case 34:
      if (lookahead == 'A') ADVANCE(92);
      END_STATE();
    case 35:
      if (lookahead == 'A') ADVANCE(154);
      END_STATE();
    case 36:
      if (lookahead == 'A') ADVANCE(104);
      END_STATE();
    case 37:
      if (lookahead == 'A') ADVANCE(94);
      END_STATE();
    case 38:
      if (lookahead == 'A') ADVANCE(167);
      END_STATE();
    case 39:
      if (lookahead == 'B') ADVANCE(223);
      END_STATE();
    case 40:
      if (lookahead == 'B') ADVANCE(87);
      END_STATE();
    case 41:
      if (lookahead == 'C') ADVANCE(231);
      END_STATE();
    case 42:
      if (lookahead == 'C') ADVANCE(110);
      END_STATE();
    case 43:
      if (lookahead == 'C') ADVANCE(112);
      END_STATE();
    case 44:
      if (lookahead == 'C') ADVANCE(163);
      END_STATE();
    case 45:
      if (lookahead == 'C') ADVANCE(101);
      END_STATE();
    case 46:
      if (lookahead == 'C') ADVANCE(38);
      END_STATE();
    case 47:
      if (lookahead == 'C') ADVANCE(62);
      END_STATE();
    case 48:
      if (lookahead == 'D') ADVANCE(229);
      END_STATE();
    case 49:
      if (lookahead == 'D') ADVANCE(85);
      END_STATE();
    case 50:
      if (lookahead == 'E') ADVANCE(223);
      END_STATE();
    case 51:
      if (lookahead == 'E') ADVANCE(151);
      END_STATE();
    case 52:
      if (lookahead == 'E') ADVANCE(68);
      if (lookahead == 'P') ADVANCE(43);
      if (lookahead == 'U') ADVANCE(142);
      END_STATE();
    case 53:
      if (lookahead == 'E') ADVANCE(224);
      END_STATE();
    case 54:
      if (lookahead == 'E') ADVANCE(227);
      END_STATE();
    case 55:
      if (lookahead == 'E') ADVANCE(229);
      END_STATE();
    case 56:
      if (lookahead == 'E') ADVANCE(226);
      END_STATE();
    case 57:
      if (lookahead == 'E') ADVANCE(214);
      END_STATE();
    case 58:
      if (lookahead == 'E') ADVANCE(215);
      END_STATE();
    case 59:
      if (lookahead == 'E') ADVANCE(208);
      END_STATE();
    case 60:
      if (lookahead == 'E') ADVANCE(117);
      END_STATE();
    case 61:
      if (lookahead == 'E') ADVANCE(228);
      END_STATE();
    case 62:
      if (lookahead == 'E') ADVANCE(48);
      END_STATE();
    case 63:
      if (lookahead == 'E') ADVANCE(168);
      END_STATE();
    case 64:
      if (lookahead == 'E') ADVANCE(26);
      if (lookahead == 'O') ADVANCE(119);
      if (lookahead == 'T') ADVANCE(152);
      END_STATE();
    case 65:
      if (lookahead == 'E') ADVANCE(26);
      if (lookahead == 'O') ADVANCE(125);
      END_STATE();
    case 66:
      if (lookahead == 'E') ADVANCE(44);
      END_STATE();
    case 67:
      if (lookahead == 'E') ADVANCE(159);
      END_STATE();
    case 68:
      if (lookahead == 'F') ADVANCE(27);
      END_STATE();
    case 69:
      if (lookahead == 'G') ADVANCE(111);
      END_STATE();
    case 70:
      if (lookahead == 'G') ADVANCE(121);
      END_STATE();
    case 71:
      if (lookahead == 'G') ADVANCE(147);
      END_STATE();
    case 72:
      if (lookahead == 'G') ADVANCE(57);
      END_STATE();
    case 73:
      if (lookahead == 'G') ADVANCE(113);
      END_STATE();
    case 74:
      if (lookahead == 'I') ADVANCE(118);
      if (lookahead == 'O') ADVANCE(181);
      END_STATE();
    case 75:
      if (lookahead == 'I') ADVANCE(146);
      END_STATE();
    case 76:
      if (lookahead == 'I') ADVANCE(146);
      if (lookahead == 'O') ADVANCE(93);
      END_STATE();
    case 77:
      if (lookahead == 'I') ADVANCE(39);
      END_STATE();
    case 78:
      if (lookahead == 'I') ADVANCE(70);
      END_STATE();
    case 79:
      if (lookahead == 'I') ADVANCE(70);
      if (lookahead == 'L') ADVANCE(224);
      END_STATE();
    case 80:
      if (lookahead == 'I') ADVANCE(165);
      END_STATE();
    case 81:
      if (lookahead == 'I') ADVANCE(96);
      END_STATE();
    case 82:
      if (lookahead == 'I') ADVANCE(96);
      if (lookahead == 'R') ADVANCE(171);
      END_STATE();
    case 83:
      if (lookahead == 'I') ADVANCE(46);
      END_STATE();
    case 84:
      if (lookahead == 'I') ADVANCE(162);
      END_STATE();
    case 85:
      if (lookahead == 'I') ADVANCE(173);
      END_STATE();
    case 86:
      if (lookahead == 'I') ADVANCE(105);
      if (lookahead == 'R') ADVANCE(175);
      END_STATE();
    case 87:
      if (lookahead == 'J') ADVANCE(66);
      END_STATE();
    case 88:
      if (lookahead == 'L') ADVANCE(79);
      if (lookahead == 'P') ADVANCE(90);
      if (lookahead == 'U') ADVANCE(160);
      END_STATE();
    case 89:
      if (lookahead == 'L') ADVANCE(224);
      END_STATE();
    case 90:
      if (lookahead == 'L') ADVANCE(77);
      END_STATE();
    case 91:
      if (lookahead == 'L') ADVANCE(232);
      END_STATE();
    case 92:
      if (lookahead == 'L') ADVANCE(231);
      END_STATE();
    case 93:
      if (lookahead == 'L') ADVANCE(172);
      END_STATE();
    case 94:
      if (lookahead == 'L') ADVANCE(153);
      END_STATE();
    case 95:
      if (lookahead == 'L') ADVANCE(153);
      if (lookahead == 'S') ADVANCE(156);
      END_STATE();
    case 96:
      if (lookahead == 'L') ADVANCE(55);
      END_STATE();
    case 97:
      if (lookahead == 'L') ADVANCE(83);
      END_STATE();
    case 98:
      if (lookahead == 'L') ADVANCE(28);
      END_STATE();
    case 99:
      if (lookahead == 'L') ADVANCE(158);
      END_STATE();
    case 100:
      if (lookahead == 'L') ADVANCE(78);
      END_STATE();
    case 101:
      if (lookahead == 'L') ADVANCE(54);
      END_STATE();
    case 102:
      if (lookahead == 'L') ADVANCE(89);
      END_STATE();
    case 103:
      if (lookahead == 'L') ADVANCE(89);
      if (lookahead == 'P') ADVANCE(90);
      if (lookahead == 'U') ADVANCE(160);
      END_STATE();
    case 104:
      if (lookahead == 'L') ADVANCE(63);
      END_STATE();
    case 105:
      if (lookahead == 'L') ADVANCE(60);
      END_STATE();
    case 106:
      if (lookahead == 'L') ADVANCE(131);
      END_STATE();
    case 107:
      if (lookahead == 'L') ADVANCE(131);
      if (lookahead == 'P') ADVANCE(148);
      END_STATE();
    case 108:
      if (lookahead == 'L') ADVANCE(155);
      END_STATE();
    case 109:
      if (lookahead == 'M') ADVANCE(230);
      END_STATE();
    case 110:
      if (lookahead == 'M') ADVANCE(235);
      END_STATE();
    case 111:
      if (lookahead == 'M') ADVANCE(216);
      END_STATE();
    case 112:
      if (lookahead == 'M') ADVANCE(15);
      END_STATE();
    case 113:
      if (lookahead == 'M') ADVANCE(234);
      END_STATE();
    case 114:
      if (lookahead == 'M') ADVANCE(29);
      END_STATE();
    case 115:
      if (lookahead == 'M') ADVANCE(120);
      END_STATE();
    case 116:
      if (lookahead == 'M') ADVANCE(25);
      END_STATE();
    case 117:
      if (lookahead == 'M') ADVANCE(32);
      if (lookahead == 'S') ADVANCE(67);
      END_STATE();
    case 118:
      if (lookahead == 'N') ADVANCE(219);
      if (lookahead == 'T') ADVANCE(116);
      END_STATE();
    case 119:
      if (lookahead == 'N') ADVANCE(50);
      END_STATE();
    case 120:
      if (lookahead == 'N') ADVANCE(225);
      END_STATE();
    case 121:
      if (lookahead == 'N') ADVANCE(220);
      END_STATE();
    case 122:
      if (lookahead == 'N') ADVANCE(71);
      END_STATE();
    case 123:
      if (lookahead == 'N') ADVANCE(55);
      END_STATE();
    case 124:
      if (lookahead == 'N') ADVANCE(47);
      END_STATE();
    case 125:
      if (lookahead == 'N') ADVANCE(54);
      END_STATE();
    case 126:
      if (lookahead == 'N') ADVANCE(53);
      END_STATE();
    case 127:
      if (lookahead == 'O') ADVANCE(223);
      END_STATE();
    case 128:
      if (lookahead == 'O') ADVANCE(180);
      END_STATE();
    case 129:
      if (lookahead == 'O') ADVANCE(231);
      END_STATE();
    case 130:
      if (lookahead == 'O') ADVANCE(119);
      END_STATE();
    case 131:
      if (lookahead == 'O') ADVANCE(179);
      END_STATE();
    case 132:
      if (lookahead == 'O') ADVANCE(170);
      END_STATE();
    case 133:
      if (lookahead == 'O') ADVANCE(123);
      END_STATE();
    case 134:
      if (lookahead == 'O') ADVANCE(126);
      END_STATE();
    case 135:
      if (lookahead == 'P') ADVANCE(90);
      if (lookahead == 'U') ADVANCE(160);
      END_STATE();
    case 136:
      if (lookahead == 'P') ADVANCE(212);
      END_STATE();
    case 137:
      if (lookahead == 'P') ADVANCE(212);
      if (lookahead == 'X') ADVANCE(230);
      END_STATE();
    case 138:
      if (lookahead == 'P') ADVANCE(209);
      END_STATE();
    case 139:
      if (lookahead == 'P') ADVANCE(221);
      END_STATE();
    case 140:
      if (lookahead == 'P') ADVANCE(211);
      END_STATE();
    case 141:
      if (lookahead == 'P') ADVANCE(148);
      END_STATE();
    case 142:
      if (lookahead == 'P') ADVANCE(97);
      END_STATE();
    case 143:
      if (lookahead == 'P') ADVANCE(149);
      END_STATE();
    case 144:
      if (lookahead == 'R') ADVANCE(171);
      END_STATE();
    case 145:
      if (lookahead == 'R') ADVANCE(222);
      END_STATE();
    case 146:
      if (lookahead == 'R') ADVANCE(45);
      END_STATE();
    case 147:
      if (lookahead == 'R') ADVANCE(132);
      END_STATE();
    case 148:
      if (lookahead == 'R') ADVANCE(80);
      END_STATE();
    case 149:
      if (lookahead == 'R') ADVANCE(84);
      END_STATE();
    case 150:
      if (lookahead == 'S') ADVANCE(213);
      END_STATE();
    case 151:
      if (lookahead == 'S') ADVANCE(156);
      END_STATE();
    case 152:
      if (lookahead == 'S') ADVANCE(41);
      END_STATE();
    case 153:
      if (lookahead == 'S') ADVANCE(56);
      END_STATE();
    case 154:
      if (lookahead == 'S') ADVANCE(157);
      END_STATE();
    case 155:
      if (lookahead == 'S') ADVANCE(61);
      END_STATE();
    case 156:
      if (lookahead == 'T') ADVANCE(223);
      END_STATE();
    case 157:
      if (lookahead == 'T') ADVANCE(230);
      END_STATE();
    case 158:
      if (lookahead == 'T') ADVANCE(233);
      END_STATE();
    case 159:
      if (lookahead == 'T') ADVANCE(210);
      END_STATE();
    case 160:
      if (lookahead == 'T') ADVANCE(127);
      END_STATE();
    case 161:
      if (lookahead == 'T') ADVANCE(152);
      END_STATE();
    case 162:
      if (lookahead == 'T') ADVANCE(55);
      END_STATE();
    case 163:
      if (lookahead == 'T') ADVANCE(150);
      END_STATE();
    case 164:
      if (lookahead == 'T') ADVANCE(129);
      END_STATE();
    case 165:
      if (lookahead == 'T') ADVANCE(58);
      END_STATE();
    case 166:
      if (lookahead == 'T') ADVANCE(59);
      END_STATE();
    case 167:
      if (lookahead == 'T') ADVANCE(53);
      END_STATE();
    case 168:
      if (lookahead == 'T') ADVANCE(166);
      END_STATE();
    case 169:
      if (lookahead == 'U') ADVANCE(142);
      END_STATE();
    case 170:
      if (lookahead == 'U') ADVANCE(139);
      END_STATE();
    case 171:
      if (lookahead == 'U') ADVANCE(56);
      END_STATE();
    case 172:
      if (lookahead == 'U') ADVANCE(115);
      END_STATE();
    case 173:
      if (lookahead == 'U') ADVANCE(109);
      END_STATE();
    case 174:
      if (lookahead == 'U') ADVANCE(99);
      END_STATE();
    case 175:
      if (lookahead == 'U') ADVANCE(61);
      END_STATE();
    case 176:
      if (lookahead == 'U') ADVANCE(164);
      END_STATE();
    case 177:
      if (lookahead == 'V') ADVANCE(218);
      END_STATE();
    case 178:
      if (lookahead == 'W') ADVANCE(223);
      END_STATE();
    case 179:
      if (lookahead == 'W') ADVANCE(230);
      END_STATE();
    case 180:
      if (lookahead == 'W') ADVANCE(225);
      END_STATE();
    case 181:
      if (lookahead == 'X') ADVANCE(227);
      END_STATE();
    case 182:
      if (lookahead == 'X') ADVANCE(230);
      END_STATE();
    case 183:
      if (lookahead == 'Z') ADVANCE(16);
      END_STATE();
    case 184:
      if (lookahead == 'b') ADVANCE(188);
      END_STATE();
    case 185:
      if (lookahead == 'o') ADVANCE(186);
      END_STATE();
    case 186:
      if (lookahead == 'r') ADVANCE(187);
      END_STATE();
    case 187:
      if (lookahead == 't') ADVANCE(184);
      END_STATE();
    case 188:
      if (lookahead == 'y') ADVANCE(17);
      END_STATE();
    case 189:
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(9);
      END_STATE();
    case 190:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(201);
      END_STATE();
    case 191:
      if (eof) ADVANCE(192);
      ADVANCE_MAP(
        '\n', 194,
        '\r', 1,
        '"', 196,
        '#', 193,
        '/', 12,
        '0', 202,
        'A', 100,
        'B', 74,
        'C', 75,
        'F', 33,
        'I', 114,
        'M', 31,
        'N', 65,
        'O', 40,
        'P', 36,
        'S', 141,
        'T', 86,
        'U', 122,
        'W', 21,
        'X', 69,
        '[', 204,
        ']', 206,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(191);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(203);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(193);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(195);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == 's') ADVANCE(185);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '#') ADVANCE(193);
      if (lookahead == '/') ADVANCE(200);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(199);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(198);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '/') ADVANCE(193);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(aux_sym_string_literal_token2);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_integer_literal);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(203);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_sortby_expression);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym_keyword_palette);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym_keyword_bitmap);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(sym_keyword_tileset);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(sym_keyword_tilemap);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(sym_keyword_map);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(sym_keyword_objects);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(sym_keyword_image);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(sym_keyword_sprite);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(sym_keyword_xgm);
      if (lookahead == '2') ADVANCE(217);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(sym_keyword_xgm2);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(sym_keyword_wav);
      END_STATE();
    case 219:
      ACCEPT_TOKEN(sym_keyword_bin);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(sym_keyword_align);
      END_STATE();
    case 221:
      ACCEPT_TOKEN(sym_keyword_ungroup);
      END_STATE();
    case 222:
      ACCEPT_TOKEN(sym_keyword_near);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(sym_keyword_compression);
      END_STATE();
    case 224:
      ACCEPT_TOKEN(sym_keyword_optimization);
      END_STATE();
    case 225:
      ACCEPT_TOKEN(sym_keyword_ordering);
      END_STATE();
    case 226:
      ACCEPT_TOKEN(sym_keyword_export);
      END_STATE();
    case 227:
      ACCEPT_TOKEN(sym_keyword_collision);
      END_STATE();
    case 228:
      ACCEPT_TOKEN(aux_sym_keyword_far_token1);
      END_STATE();
    case 229:
      ACCEPT_TOKEN(sym_keyword_sprite_optimization_type);
      END_STATE();
    case 230:
      ACCEPT_TOKEN(sym_keyword_sprite_optimization_level);
      END_STATE();
    case 231:
      ACCEPT_TOKEN(sym_keyword_xgm_timing);
      END_STATE();
    case 232:
      ACCEPT_TOKEN(sym_keyword_xgm_timing);
      if (lookahead == 'E') ADVANCE(168);
      END_STATE();
    case 233:
      ACCEPT_TOKEN(sym_keyword_wav_driver);
      END_STATE();
    case 234:
      ACCEPT_TOKEN(sym_keyword_wav_driver);
      if (lookahead == '2') ADVANCE(233);
      END_STATE();
    case 235:
      ACCEPT_TOKEN(sym_keyword_wav_driver);
      if (lookahead == '4') ADVANCE(233);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 191},
  [2] = {.lex_state = 191},
  [3] = {.lex_state = 191},
  [4] = {.lex_state = 191},
  [5] = {.lex_state = 191},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 191},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 10},
  [13] = {.lex_state = 10},
  [14] = {.lex_state = 191},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 191},
  [18] = {.lex_state = 191},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 191},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 10},
  [25] = {.lex_state = 191},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 191},
  [29] = {.lex_state = 191},
  [30] = {.lex_state = 191},
  [31] = {.lex_state = 191},
  [32] = {.lex_state = 191},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 191},
  [35] = {.lex_state = 191},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 191},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 191},
  [43] = {.lex_state = 191},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 191},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 191},
  [50] = {.lex_state = 191},
  [51] = {.lex_state = 191},
  [52] = {.lex_state = 191},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 191},
  [55] = {.lex_state = 7},
  [56] = {.lex_state = 191},
  [57] = {.lex_state = 191},
  [58] = {.lex_state = 191},
  [59] = {.lex_state = 191},
  [60] = {.lex_state = 191},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 191},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 191},
  [66] = {.lex_state = 191},
  [67] = {.lex_state = 191},
  [68] = {.lex_state = 191},
  [69] = {.lex_state = 191},
  [70] = {.lex_state = 191},
  [71] = {.lex_state = 191},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 191},
  [74] = {.lex_state = 191},
  [75] = {.lex_state = 191},
  [76] = {.lex_state = 8},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 191},
  [79] = {.lex_state = 191},
  [80] = {.lex_state = 4},
  [81] = {.lex_state = 4},
  [82] = {.lex_state = 3},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 191},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 191},
  [91] = {.lex_state = 11},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 11},
  [98] = {.lex_state = 191},
  [99] = {.lex_state = 191},
  [100] = {.lex_state = 11},
  [101] = {.lex_state = 3},
  [102] = {.lex_state = 191},
  [103] = {.lex_state = 11},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 11},
  [107] = {.lex_state = 11},
  [108] = {.lex_state = 11},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 11},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 11},
  [115] = {.lex_state = 11},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 11},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 11},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_newline] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_literal_token2] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_sortby_expression] = ACTIONS(1),
    [sym_keyword_palette] = ACTIONS(1),
    [sym_keyword_bitmap] = ACTIONS(1),
    [sym_keyword_map] = ACTIONS(1),
    [sym_keyword_objects] = ACTIONS(1),
    [sym_keyword_image] = ACTIONS(1),
    [sym_keyword_sprite] = ACTIONS(1),
    [sym_keyword_xgm] = ACTIONS(1),
    [sym_keyword_xgm2] = ACTIONS(1),
    [sym_keyword_wav] = ACTIONS(1),
    [sym_keyword_bin] = ACTIONS(1),
    [sym_keyword_align] = ACTIONS(1),
    [sym_keyword_ungroup] = ACTIONS(1),
    [sym_keyword_near] = ACTIONS(1),
    [sym_keyword_compression] = ACTIONS(1),
    [sym_keyword_optimization] = ACTIONS(1),
    [sym_keyword_ordering] = ACTIONS(1),
    [sym_keyword_export] = ACTIONS(1),
    [sym_keyword_collision] = ACTIONS(1),
    [aux_sym_keyword_far_token1] = ACTIONS(1),
    [sym_keyword_sprite_optimization_type] = ACTIONS(1),
    [sym_keyword_sprite_optimization_level] = ACTIONS(1),
    [sym_keyword_xgm_timing] = ACTIONS(1),
    [sym_keyword_wav_driver] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(88),
    [sym__statement] = STATE(2),
    [sym_palette_statement] = STATE(93),
    [sym_bitmap_statement] = STATE(93),
    [sym_tileset_statement] = STATE(93),
    [sym_tilemap_statement] = STATE(93),
    [sym_map_statement] = STATE(93),
    [sym_objects_statement] = STATE(93),
    [sym_image_statement] = STATE(93),
    [sym_sprite_statement] = STATE(93),
    [sym_xgm_statement] = STATE(93),
    [sym_xgm2_statement] = STATE(93),
    [sym_wav_statement] = STATE(93),
    [sym_bin_statement] = STATE(93),
    [sym_align_statement] = STATE(93),
    [sym_ungroup_statement] = STATE(93),
    [sym_near_statement] = STATE(93),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [sym_keyword_palette] = ACTIONS(7),
    [sym_keyword_bitmap] = ACTIONS(9),
    [sym_keyword_tileset] = ACTIONS(11),
    [sym_keyword_tilemap] = ACTIONS(13),
    [sym_keyword_map] = ACTIONS(15),
    [sym_keyword_objects] = ACTIONS(17),
    [sym_keyword_image] = ACTIONS(19),
    [sym_keyword_sprite] = ACTIONS(21),
    [sym_keyword_xgm] = ACTIONS(23),
    [sym_keyword_xgm2] = ACTIONS(25),
    [sym_keyword_wav] = ACTIONS(27),
    [sym_keyword_bin] = ACTIONS(29),
    [sym_keyword_align] = ACTIONS(31),
    [sym_keyword_ungroup] = ACTIONS(33),
    [sym_keyword_near] = ACTIONS(35),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(3),
    [sym_palette_statement] = STATE(93),
    [sym_bitmap_statement] = STATE(93),
    [sym_tileset_statement] = STATE(93),
    [sym_tilemap_statement] = STATE(93),
    [sym_map_statement] = STATE(93),
    [sym_objects_statement] = STATE(93),
    [sym_image_statement] = STATE(93),
    [sym_sprite_statement] = STATE(93),
    [sym_xgm_statement] = STATE(93),
    [sym_xgm2_statement] = STATE(93),
    [sym_wav_statement] = STATE(93),
    [sym_bin_statement] = STATE(93),
    [sym_align_statement] = STATE(93),
    [sym_ungroup_statement] = STATE(93),
    [sym_near_statement] = STATE(93),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_comment] = ACTIONS(3),
    [sym_keyword_palette] = ACTIONS(7),
    [sym_keyword_bitmap] = ACTIONS(9),
    [sym_keyword_tileset] = ACTIONS(11),
    [sym_keyword_tilemap] = ACTIONS(13),
    [sym_keyword_map] = ACTIONS(15),
    [sym_keyword_objects] = ACTIONS(17),
    [sym_keyword_image] = ACTIONS(19),
    [sym_keyword_sprite] = ACTIONS(21),
    [sym_keyword_xgm] = ACTIONS(23),
    [sym_keyword_xgm2] = ACTIONS(25),
    [sym_keyword_wav] = ACTIONS(27),
    [sym_keyword_bin] = ACTIONS(29),
    [sym_keyword_align] = ACTIONS(31),
    [sym_keyword_ungroup] = ACTIONS(33),
    [sym_keyword_near] = ACTIONS(35),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(3),
    [sym_palette_statement] = STATE(93),
    [sym_bitmap_statement] = STATE(93),
    [sym_tileset_statement] = STATE(93),
    [sym_tilemap_statement] = STATE(93),
    [sym_map_statement] = STATE(93),
    [sym_objects_statement] = STATE(93),
    [sym_image_statement] = STATE(93),
    [sym_sprite_statement] = STATE(93),
    [sym_xgm_statement] = STATE(93),
    [sym_xgm2_statement] = STATE(93),
    [sym_wav_statement] = STATE(93),
    [sym_bin_statement] = STATE(93),
    [sym_align_statement] = STATE(93),
    [sym_ungroup_statement] = STATE(93),
    [sym_near_statement] = STATE(93),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(39),
    [sym_comment] = ACTIONS(3),
    [sym_keyword_palette] = ACTIONS(41),
    [sym_keyword_bitmap] = ACTIONS(44),
    [sym_keyword_tileset] = ACTIONS(47),
    [sym_keyword_tilemap] = ACTIONS(50),
    [sym_keyword_map] = ACTIONS(53),
    [sym_keyword_objects] = ACTIONS(56),
    [sym_keyword_image] = ACTIONS(59),
    [sym_keyword_sprite] = ACTIONS(62),
    [sym_keyword_xgm] = ACTIONS(65),
    [sym_keyword_xgm2] = ACTIONS(68),
    [sym_keyword_wav] = ACTIONS(71),
    [sym_keyword_bin] = ACTIONS(74),
    [sym_keyword_align] = ACTIONS(77),
    [sym_keyword_ungroup] = ACTIONS(80),
    [sym_keyword_near] = ACTIONS(83),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym_keyword_xgm,
    ACTIONS(86), 15,
      ts_builtin_sym_end,
      sym_keyword_palette,
      sym_keyword_bitmap,
      sym_keyword_tileset,
      sym_keyword_tilemap,
      sym_keyword_map,
      sym_keyword_objects,
      sym_keyword_image,
      sym_keyword_sprite,
      sym_keyword_xgm2,
      sym_keyword_wav,
      sym_keyword_bin,
      sym_keyword_align,
      sym_keyword_ungroup,
      sym_keyword_near,
  [24] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym_newline,
    ACTIONS(92), 1,
      sym_integer_literal,
    ACTIONS(94), 1,
      anon_sym_LBRACK,
    STATE(68), 1,
      sym_sprite_time_expression,
    STATE(66), 2,
      sym_integer_array_literal,
      sym_integer_array2d_literal,
  [44] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_LBRACK,
    ACTIONS(99), 1,
      anon_sym_RBRACK,
    STATE(6), 2,
      sym_integer_array_literal,
      aux_sym_integer_array2d_literal_repeat1,
  [58] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 4,
      sym_newline,
      anon_sym_DQUOTE,
      sym_keyword_compression,
      sym_keyword_wav_driver,
  [68] = 4,
    ACTIONS(103), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(107), 2,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
  [82] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_newline,
    ACTIONS(111), 1,
      anon_sym_DQUOTE,
    ACTIONS(113), 1,
      sym_sortby_expression,
    STATE(31), 1,
      sym_string_literal,
  [98] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym_newline,
    ACTIONS(117), 1,
      anon_sym_DQUOTE,
    STATE(10), 1,
      aux_sym_xgm2_statement_repeat1,
    STATE(42), 1,
      sym_string_literal,
  [114] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 4,
      sym_newline,
      anon_sym_DQUOTE,
      sym_keyword_compression,
      sym_keyword_wav_driver,
  [124] = 4,
    ACTIONS(103), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(124), 2,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
  [138] = 4,
    ACTIONS(103), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_DQUOTE,
    STATE(8), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(129), 2,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
  [152] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      sym_integer_literal,
    ACTIONS(133), 1,
      anon_sym_LBRACK,
    STATE(16), 2,
      sym_integer_array_literal,
      aux_sym_integer_array2d_literal_repeat1,
  [166] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_DQUOTE,
    ACTIONS(101), 3,
      sym_newline,
      sym_integer_literal,
      sym_sortby_expression,
  [178] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_LBRACK,
    ACTIONS(137), 1,
      anon_sym_RBRACK,
    STATE(6), 2,
      sym_integer_array_literal,
      aux_sym_integer_array2d_literal_repeat1,
  [192] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_newline,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    STATE(10), 1,
      aux_sym_xgm2_statement_repeat1,
    STATE(42), 1,
      sym_string_literal,
  [208] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 4,
      sym_newline,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_keyword_collision,
  [218] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_DQUOTE,
    ACTIONS(120), 3,
      sym_newline,
      sym_integer_literal,
      sym_sortby_expression,
  [230] = 4,
    ACTIONS(103), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_DQUOTE,
    STATE(22), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(149), 2,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
  [244] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 4,
      sym_newline,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_keyword_collision,
  [254] = 4,
    ACTIONS(103), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(107), 2,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
  [268] = 4,
    ACTIONS(103), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_DQUOTE,
    STATE(24), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(157), 2,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
  [282] = 4,
    ACTIONS(103), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(107), 2,
      aux_sym_string_literal_token1,
      aux_sym_string_literal_token2,
  [296] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    STATE(17), 1,
      aux_sym_xgm2_statement_repeat1,
    STATE(42), 1,
      sym_string_literal,
  [309] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      sym_newline,
    ACTIONS(164), 1,
      sym_keyword_compression,
    ACTIONS(166), 1,
      sym_keyword_optimization,
  [322] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      sym_newline,
    ACTIONS(171), 1,
      sym_integer_literal,
    ACTIONS(173), 1,
      sym_keyword_compression,
  [335] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    ACTIONS(175), 1,
      sym_newline,
    STATE(92), 1,
      sym_string_literal,
  [348] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym_newline,
    ACTIONS(179), 1,
      aux_sym_keyword_far_token1,
    STATE(117), 1,
      sym_keyword_far,
  [361] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    ACTIONS(181), 1,
      sym_newline,
    STATE(32), 1,
      sym_string_literal,
  [374] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    ACTIONS(183), 1,
      sym_newline,
    STATE(89), 1,
      sym_string_literal,
  [387] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    ACTIONS(185), 1,
      sym_newline,
    STATE(96), 1,
      sym_string_literal,
  [400] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_COMMA,
    ACTIONS(189), 1,
      anon_sym_RBRACK,
    STATE(37), 1,
      aux_sym_integer_array_literal_repeat1,
  [413] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      sym_newline,
    ACTIONS(193), 1,
      aux_sym_keyword_far_token1,
    STATE(113), 1,
      sym_keyword_sprite_optimization_duplicate,
  [426] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 1,
      aux_sym_keyword_far_token1,
    ACTIONS(195), 1,
      sym_newline,
    STATE(122), 1,
      sym_keyword_far,
  [439] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_RBRACK,
    STATE(36), 1,
      aux_sym_integer_array_literal_repeat1,
  [452] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_COMMA,
    ACTIONS(202), 1,
      anon_sym_RBRACK,
    STATE(36), 1,
      aux_sym_integer_array_literal_repeat1,
  [465] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym_newline,
    ACTIONS(206), 1,
      sym_keyword_ordering,
  [475] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      sym_string_literal,
  [485] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_newline,
    ACTIONS(210), 1,
      sym_keyword_compression,
  [495] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      sym_newline,
    ACTIONS(214), 1,
      sym_keyword_xgm_timing,
  [505] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 2,
      sym_newline,
      anon_sym_DQUOTE,
  [513] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      sym_newline,
    ACTIONS(220), 1,
      sym_integer_literal,
  [523] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      sym_newline,
    ACTIONS(224), 1,
      sym_keyword_optimization,
  [533] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      sym_newline,
    ACTIONS(229), 1,
      sym_keyword_compression,
  [543] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      sym_newline,
    ACTIONS(234), 1,
      sym_keyword_compression,
  [553] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_DQUOTE,
    STATE(9), 1,
      sym_string_literal,
  [563] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym_newline,
    ACTIONS(240), 1,
      sym_keyword_optimization,
  [573] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      sym_newline,
    ACTIONS(244), 1,
      sym_integer_literal,
  [583] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      sym_newline,
    ACTIONS(248), 1,
      sym_integer_literal,
  [593] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      sym_newline,
    ACTIONS(252), 1,
      sym_integer_literal,
  [603] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_newline,
    ACTIONS(256), 1,
      sym_integer_literal,
  [613] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      sym_newline,
    ACTIONS(260), 1,
      sym_keyword_compression,
  [623] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      sym_newline,
    ACTIONS(264), 1,
      sym_integer_literal,
  [633] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      sym_newline,
    ACTIONS(268), 1,
      sym_keyword_export,
  [643] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_newline,
    ACTIONS(272), 1,
      sym_integer_literal,
  [653] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      sym_newline,
    ACTIONS(276), 1,
      sym_integer_literal,
  [663] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    STATE(46), 1,
      sym_string_literal,
  [673] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    STATE(119), 1,
      sym_string_literal,
  [683] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    STATE(82), 1,
      sym_string_literal,
  [693] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      sym_newline,
    ACTIONS(280), 1,
      sym_keyword_compression,
  [703] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    STATE(45), 1,
      sym_string_literal,
  [713] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      sym_newline,
    ACTIONS(284), 1,
      sym_keyword_ordering,
  [723] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      sym_newline,
    ACTIONS(288), 1,
      sym_keyword_ordering,
  [733] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    STATE(83), 1,
      sym_string_literal,
  [743] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 2,
      sym_newline,
      sym_keyword_collision,
  [751] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    STATE(62), 1,
      sym_string_literal,
  [761] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      sym_newline,
    ACTIONS(294), 1,
      sym_keyword_collision,
  [771] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    STATE(58), 1,
      sym_string_literal,
  [781] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    STATE(39), 1,
      sym_string_literal,
  [791] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      sym_string_literal,
  [801] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      sym_newline,
    ACTIONS(298), 1,
      sym_keyword_sprite_optimization_type,
  [811] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_DQUOTE,
    STATE(90), 1,
      sym_string_literal,
  [821] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      sym_string_literal,
  [831] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 2,
      sym_newline,
      sym_keyword_collision,
  [839] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      sym_newline,
    ACTIONS(306), 1,
      sym_keyword_sprite_optimization_level,
  [849] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [857] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      anon_sym_DQUOTE,
    STATE(101), 1,
      sym_string_literal,
  [867] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_DQUOTE,
    STATE(43), 1,
      sym_string_literal,
  [877] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      sym_newline,
      sym_keyword_xgm_timing,
  [885] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 2,
      sym_newline,
      sym_keyword_xgm_timing,
  [893] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      sym_newline,
    ACTIONS(310), 1,
      sym_keyword_compression,
  [903] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      sym_newline,
    ACTIONS(314), 1,
      sym_keyword_compression,
  [913] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      sym_newline,
    ACTIONS(318), 1,
      sym_integer_literal,
  [923] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      sym_newline,
  [930] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      sym_newline,
  [937] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      sym_newline,
  [944] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      ts_builtin_sym_end,
  [951] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      sym_newline,
  [958] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      sym_integer_literal,
  [965] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      sym_identifier,
  [972] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      sym_newline,
  [979] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      sym_newline,
  [986] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      sym_newline,
  [993] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(340), 1,
      sym_newline,
  [1000] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(342), 1,
      sym_newline,
  [1007] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(344), 1,
      sym_identifier,
  [1014] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      sym_integer_literal,
  [1021] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(346), 1,
      sym_integer_literal,
  [1028] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(348), 1,
      sym_identifier,
  [1035] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(350), 1,
      sym_keyword_wav_driver,
  [1042] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(352), 1,
      sym_integer_literal,
  [1049] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(354), 1,
      sym_identifier,
  [1056] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(356), 1,
      sym_newline,
  [1063] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(358), 1,
      sym_newline,
  [1070] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(360), 1,
      sym_identifier,
  [1077] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(362), 1,
      sym_identifier,
  [1084] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(364), 1,
      sym_identifier,
  [1091] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(366), 1,
      sym_newline,
  [1098] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(368), 1,
      sym_identifier,
  [1105] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(370), 1,
      sym_newline,
  [1112] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(372), 1,
      sym_newline,
  [1119] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(374), 1,
      sym_newline,
  [1126] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(376), 1,
      sym_identifier,
  [1133] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(378), 1,
      sym_identifier,
  [1140] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(380), 1,
      sym_newline,
  [1147] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(382), 1,
      sym_newline,
  [1154] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(384), 1,
      sym_identifier,
  [1161] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(386), 1,
      sym_newline,
  [1168] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(388), 1,
      sym_identifier,
  [1175] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(390), 1,
      sym_newline,
  [1182] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(392), 1,
      sym_newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 24,
  [SMALL_STATE(6)] = 44,
  [SMALL_STATE(7)] = 58,
  [SMALL_STATE(8)] = 68,
  [SMALL_STATE(9)] = 82,
  [SMALL_STATE(10)] = 98,
  [SMALL_STATE(11)] = 114,
  [SMALL_STATE(12)] = 124,
  [SMALL_STATE(13)] = 138,
  [SMALL_STATE(14)] = 152,
  [SMALL_STATE(15)] = 166,
  [SMALL_STATE(16)] = 178,
  [SMALL_STATE(17)] = 192,
  [SMALL_STATE(18)] = 208,
  [SMALL_STATE(19)] = 218,
  [SMALL_STATE(20)] = 230,
  [SMALL_STATE(21)] = 244,
  [SMALL_STATE(22)] = 254,
  [SMALL_STATE(23)] = 268,
  [SMALL_STATE(24)] = 282,
  [SMALL_STATE(25)] = 296,
  [SMALL_STATE(26)] = 309,
  [SMALL_STATE(27)] = 322,
  [SMALL_STATE(28)] = 335,
  [SMALL_STATE(29)] = 348,
  [SMALL_STATE(30)] = 361,
  [SMALL_STATE(31)] = 374,
  [SMALL_STATE(32)] = 387,
  [SMALL_STATE(33)] = 400,
  [SMALL_STATE(34)] = 413,
  [SMALL_STATE(35)] = 426,
  [SMALL_STATE(36)] = 439,
  [SMALL_STATE(37)] = 452,
  [SMALL_STATE(38)] = 465,
  [SMALL_STATE(39)] = 475,
  [SMALL_STATE(40)] = 485,
  [SMALL_STATE(41)] = 495,
  [SMALL_STATE(42)] = 505,
  [SMALL_STATE(43)] = 513,
  [SMALL_STATE(44)] = 523,
  [SMALL_STATE(45)] = 533,
  [SMALL_STATE(46)] = 543,
  [SMALL_STATE(47)] = 553,
  [SMALL_STATE(48)] = 563,
  [SMALL_STATE(49)] = 573,
  [SMALL_STATE(50)] = 583,
  [SMALL_STATE(51)] = 593,
  [SMALL_STATE(52)] = 603,
  [SMALL_STATE(53)] = 613,
  [SMALL_STATE(54)] = 623,
  [SMALL_STATE(55)] = 633,
  [SMALL_STATE(56)] = 643,
  [SMALL_STATE(57)] = 653,
  [SMALL_STATE(58)] = 663,
  [SMALL_STATE(59)] = 673,
  [SMALL_STATE(60)] = 683,
  [SMALL_STATE(61)] = 693,
  [SMALL_STATE(62)] = 703,
  [SMALL_STATE(63)] = 713,
  [SMALL_STATE(64)] = 723,
  [SMALL_STATE(65)] = 733,
  [SMALL_STATE(66)] = 743,
  [SMALL_STATE(67)] = 751,
  [SMALL_STATE(68)] = 761,
  [SMALL_STATE(69)] = 771,
  [SMALL_STATE(70)] = 781,
  [SMALL_STATE(71)] = 791,
  [SMALL_STATE(72)] = 801,
  [SMALL_STATE(73)] = 811,
  [SMALL_STATE(74)] = 821,
  [SMALL_STATE(75)] = 831,
  [SMALL_STATE(76)] = 839,
  [SMALL_STATE(77)] = 849,
  [SMALL_STATE(78)] = 857,
  [SMALL_STATE(79)] = 867,
  [SMALL_STATE(80)] = 877,
  [SMALL_STATE(81)] = 885,
  [SMALL_STATE(82)] = 893,
  [SMALL_STATE(83)] = 903,
  [SMALL_STATE(84)] = 913,
  [SMALL_STATE(85)] = 923,
  [SMALL_STATE(86)] = 930,
  [SMALL_STATE(87)] = 937,
  [SMALL_STATE(88)] = 944,
  [SMALL_STATE(89)] = 951,
  [SMALL_STATE(90)] = 958,
  [SMALL_STATE(91)] = 965,
  [SMALL_STATE(92)] = 972,
  [SMALL_STATE(93)] = 979,
  [SMALL_STATE(94)] = 986,
  [SMALL_STATE(95)] = 993,
  [SMALL_STATE(96)] = 1000,
  [SMALL_STATE(97)] = 1007,
  [SMALL_STATE(98)] = 1014,
  [SMALL_STATE(99)] = 1021,
  [SMALL_STATE(100)] = 1028,
  [SMALL_STATE(101)] = 1035,
  [SMALL_STATE(102)] = 1042,
  [SMALL_STATE(103)] = 1049,
  [SMALL_STATE(104)] = 1056,
  [SMALL_STATE(105)] = 1063,
  [SMALL_STATE(106)] = 1070,
  [SMALL_STATE(107)] = 1077,
  [SMALL_STATE(108)] = 1084,
  [SMALL_STATE(109)] = 1091,
  [SMALL_STATE(110)] = 1098,
  [SMALL_STATE(111)] = 1105,
  [SMALL_STATE(112)] = 1112,
  [SMALL_STATE(113)] = 1119,
  [SMALL_STATE(114)] = 1126,
  [SMALL_STATE(115)] = 1133,
  [SMALL_STATE(116)] = 1140,
  [SMALL_STATE(117)] = 1147,
  [SMALL_STATE(118)] = 1154,
  [SMALL_STATE(119)] = 1161,
  [SMALL_STATE(120)] = 1168,
  [SMALL_STATE(121)] = 1175,
  [SMALL_STATE(122)] = 1182,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(107),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(114),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(118),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(120),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sprite_statement, 6, 0, 30),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_integer_array2d_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_integer_array2d_literal_repeat1, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objects_statement, 5, 0, 17),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_xgm2_statement_repeat1, 2, 0, 11),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_xgm2_statement_repeat1, 2, 0, 11), SHIFT_REPEAT(13),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [124] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xgm2_statement, 3, 0, 5),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer_array_literal, 3, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer_array_literal, 4, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_tilemap_statement, 5, 0, 15), REDUCE(sym_tilemap_statement, 5, 0, 16),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [168] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_map_statement, 5, 0, 15), REDUCE(sym_map_statement, 5, 0, 16),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xgm_statement, 4, 0, 10),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wav_statement, 5, 0, 21),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objects_statement, 6, 0, 27),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objects_statement, 6, 0, 28),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objects_statement, 7, 0, 36),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sprite_statement, 10, 0, 46),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bin_statement, 7, 0, 39),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_integer_array_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_integer_array_literal_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tileset_statement, 5, 0, 14),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_image_statement, 3, 0, 3),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xgm_statement, 3, 0, 2),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_xgm2_statement_repeat1, 1, 0, 4),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bin_statement, 3, 0, 2),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tileset_statement, 4, 0, 7),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_tilemap_statement, 4, 0, 8), REDUCE(sym_tilemap_statement, 4, 0, 9),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_map_statement, 4, 0, 8), REDUCE(sym_map_statement, 4, 0, 9),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_image_statement, 4, 0, 6),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wav_statement, 4, 0, 12),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bin_statement, 4, 0, 13),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_align_statement, 1, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_image_statement, 5, 0, 18),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sprite_statement, 5, 0, 19),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bin_statement, 5, 0, 22),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tileset_statement, 6, 0, 23),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tilemap_statement, 6, 0, 24),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tilemap_statement, 6, 0, 25),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bin_statement, 6, 0, 32),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tilemap_statement, 7, 0, 35),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_statement, 7, 0, 34),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sprite_time_expression, 1, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sprite_statement, 7, 0, 38),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sprite_statement, 8, 0, 43),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer_array2d_literal, 3, 0, 0),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sprite_statement, 9, 0, 45),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bitmap_statement, 3, 0, 3),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tileset_statement, 3, 0, 2),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_statement, 6, 0, 24),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tilemap_statement, 7, 0, 34),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ungroup_statement, 1, 0, 0),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_near_statement, 1, 0, 0),
  [326] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objects_statement, 7, 0, 37),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_xgm_statement, 5, 0, 20),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [338] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tilemap_statement, 8, 0, 40),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_statement, 8, 0, 41),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_objects_statement, 8, 0, 42),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [356] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_statement, 6, 0, 26),
  [358] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bitmap_statement, 4, 0, 6),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [366] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_image_statement, 6, 0, 29),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [370] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_align_statement, 2, 0, 1),
  [372] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword_sprite_optimization_duplicate, 1, 0, 0),
  [374] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sprite_statement, 11, 0, 47),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [380] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword_far, 1, 0, 0),
  [382] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wav_statement, 6, 0, 31),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [386] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_palette_statement, 3, 0, 2),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [390] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tileset_statement, 7, 0, 33),
  [392] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bin_statement, 8, 0, 44),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rescomp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "rescomp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
